#################################################
#          horizontal pod autoscaler            #
#################################################

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: product-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product-service
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: user-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-service
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: payment-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment-service
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: db-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: db-service
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70